### ISSUE TITLE
淘宝xsign算法

### ISSUE THREAD

**Issue by junges521** [Colinlyj210/x-sign#1]
请联系我qq号951263019

**Comment by OneCodeMonkey** [comment]
有偿的吗？

**Comment by Colinlyj210** [comment]
@OneCodeMonkey  是的

**Comment by chianz** [comment]
你好 能搭建在centos服务器么

**Comment by Colinlyj210** [comment]
@chianz 不行，需要windows

**Comment by chianz** [comment]
> @chianz 不行，需要windows

那2核1G的windows2012R 服务器能搭建么 是云服务器

**Comment by Colinlyj210** [comment]
> > @chianz 不行，需要windows
> 
> 那2核1G的windows2012R 服务器能搭建么 是云服务器

加我q把
